name: E2E tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: ⬇ Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 🐍 Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: 👷 Build and install checkout
        run: |
          pip install .

      - name: 🏗 Create base config for test server
        run: |
          mkdir e2econfig
          cp -r .github/fixtures/with_acl/* e2econfig

      - name: 🚀 Run Cypress
        uses: cypress-io/github-action@v2
        with:
          working-directory: tests/cypress
          start: 'octoprint -b ${{ github.workspace }}/e2econfig serve --host 127.0.0.1 --port 5000'
          wait-on: 'http://127.0.0.1:5000/online.txt'

      - name: ⬆ Upload screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/cypress/screenshots
      - name: ⬆ Upload videos
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: tests/cypress/videos
